### ISSUE TITLE
Upgrade rest-client

### ISSUE THREAD

**Issue by rogierslag** [mollie/mollie-api-ruby#10]
Recently a vulnerability for rest-client was discovered, so upgrading to version 1.8 is strongly recommended. However this gem still forces the version down to 1.6. Can you guys test and upgrade to the newest version so we do no longer have to use a vulnerable version since it's the lowest common denominator?

I can test and create a PR if you like!

**Comment by paetor** [comment]
Thanks @rogierslag, a PR would be nice and thanks for raising this issue.
