### ISSUE TITLE
Payment list for appropriate subscription

### ISSUE THREAD

**Issue by olegsobchuk** [mollie/mollie-api-ruby#103]
How can I fetch a list of `Payment`s for appropriate `Subscription`? I found that it is possible to fetch all Payments, but in my case needed only for Subscription. API has this [endpoint](https://docs.mollie.com/reference/v2/subscriptions-api/list-subscriptions-payments).
Thanks

**Comment by justincase** [comment]
Hi, the Ruby client doesn't have this functionality yet. I'll see what I can do.
