### ISSUE TITLE
Mollie Connect Mandate Issue

### ISSUE THREAD

**Issue by rubydevteam** [mollie/mollie-api-ruby#105]
Hello,

mollie_access_token: "access_XXXXX",
mollie_refresh_token: "refresh_XXXXX",
mollie_profile_id: "pfl_XXXXX"

I've tried to create payment like this

payment = Mollie::Client.with_api_key("access_XXXXX") do
Mollie::Payment.create(
profileId:"pfl_XXXXX",
amount: { value: '110.00', currency: 'EUR' },
description: 'My first moillie connect API payment',
applicationFee: { amount: { value: '1.00', currency: 'EUR' }, description:'Application Fee' },
redirect_url: redirect_url,
webhook_url: webhook_url
)
end

but i got this error message

Mollie::RequestError: 422 Unprocessable Entity: Unable to process application request for this account

Can you please help me at what step i made mistake?, because i am not able to get my mistake from last many day and my development is delayed due to this.

It would be very helpful.

**Comment by vernondegoede** [comment]
@rubydevteam Looks like you're trying to collect application fee from your own account. Can you try the same call again using a different account / access key?

**Comment by rubydevteam** [comment]
access_token = 'test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'   //test key of the different account 
      payment = Mollie::Client.with_api_key(access_token) do
        Mollie::Payment.create(
          testmode: true,
          profileId: "pfl_XXXXXXXXX",
          amount:       { value: '110.00', currency: 'EUR' },
          description:  'My first moillie connect API payment',
          applicationFee: {amount: { value: '10.00', currency: 'EUR' }, description:'Application Fee'},
          redirect_url: redirect_url,
          webhook_url:  webhook_url
        )
      end


Now its showing me 
Mollie::RequestError: 422 Unprocessable Entity: Non-existent body parameter "testmode" for this API call. Did you mean: "method"?

**Comment by willemstuursma** [comment]
The testmode paramter is only for OAuh Access Tokens / Organization Access Tokens. When using API keys (that start with `test_` or `live_`, the `testmode` parameter is not allowed.

**Comment by jlogan** [comment]
OK great thanks. Let me try without testmode

**Comment by rubydevteam** [comment]
ohk great thanks, Let me try without testmode and will get back to you asap

Thanks

**Comment by rubydevteam** [comment]
access_token = 'test_Fun6cPUExxhbKw78BukFPrFVuebdVq'
payment = Mollie::Client.with_api_key(access_token) do
   Mollie::Payment.create(        
     profileId: "pfl_KSJWGdbW5V",          
     amount:       { value: '110.00', currency: 'EUR' },          
     description:  'My first moillie connect API payment',          
     applicationFee: {amount: { value: '10.00', currency: 'EUR' }, description:'Application Fee'},          
     redirect_url: redirect_url,          
     webhook_url:  webhook_url          
   )          
 end

Still i am getting 
Mollie::RequestError: 422 Unprocessable Entity: Non-existent body parameter "profileId" for this API call. Did you mean: "locale"?

**Comment by willemstuursma** [comment]
When using an API key, the profile is already determined by the API key and hence should also be omitted. 

To get ahead, you can also not use the `applicationFee` parameter when using an API key. You need an OAuth access token for that.
