### ISSUE TITLE
metadata for Subscription

### ISSUE THREAD

**Issue by olegsobchuk** [mollie/mollie-api-ruby#107]
for instance `Mollie::Customer::Subscription` method `metadata` is absent.

Is it possible to add method to this class?

Thx

**Comment by vernondegoede** [comment]
Thanks @olegsobchuk, we'll release a new version of the API client tomorrow, which should fix this issue.

**Comment by olegsobchuk** [comment]
@vernondegoede  wow, thx, looking forward

**Comment by vernondegoede** [comment]
@olegsobchuk Just released `4.1.5`, which allows you to use metadata within a Subscription. Let me know if you run into anything else 👍 

`gem 'mollie-api-ruby', '~> 4.1', '>= 4.1.5'`
