### ISSUE TITLE
Update list of Ruby versions to test against

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-ruby#109]
In Travis I see that we are testing against Ruby 2.1, 2.2 and 2.3.

These versions seem very old and some versions won't install our dependencies via bundler.

@justincase can you update the supported versions in `.travis.yml` to something that makes sense?

cc @vernondegoede

**Comment by justincase** [comment]
The client adds the Ruby version to the ‘User-Agent’ header. Perhaps we can use this to determine which older versions of Ruby we wish to support?

**Comment by willemstuursma** [comment]
I'll have a look when I'm back in the office.

What is the lowest Ruby version that still gets security patches?

Can you update the list with the more modern versions?

**Comment by justincase** [comment]
> What is the lowest Ruby version that still gets security patches?

Ruby 2.3 at the moment but it’s EOL at the end of the month: https://www.ruby-lang.org/en/downloads/branches/

> Can you update the list with the more modern versions?

Will do.

**Comment by willemstuursma** [comment]
Is it reasonable to drop support for < 2.3? How does the Ruby community feel about that?

**Comment by willemstuursma** [comment]
@vernondegoede can you give us some input here?

**Comment by vernondegoede** [comment]
We cannot drop support for 2.3 yet, but everything < 2.3 should be fine. Let's test against 2.3, 2.4, 2.5 and 2.6 in Travis.
