### ISSUE TITLE
Vraag metadata

### ISSUE THREAD

**Issue by ldestrooper** [mollie/mollie-api-ruby#125]
Ik ben bezig met het implementeren van de payments en heb de metadata nodig om de order_id in op te slaan.

Opslaan doe ik zo:
payment = Mollie::Payment.create(
    method:       'mistercash',
    amount:       cart_total_incl_tax,
    description:   'Uw bestelling',
    redirectUrl: checkout_status_url,
    webhookUrl:     checkout_update_url,
    customerId: @cart.user.mollie_id,
    metadata:       { order_id: @cart[:id] }
)
redirect_to payment.payment_url

Nu als ik de order_id terug wil krijgen op mijn checkout_update_url dan doe ik dit momenteel zo:
@order_id = params[:metadata][:order_id]

Echter dit lijkt niet te werken.

Hoe kan ik het order_id opvragen met params bij de redirect?

**Comment by vernondegoede** [comment]
Hi @ldestrooper,

Sla je in je database op welke Mollie payment(s) bij een order hoort/horen? Je kunt het beste een webhook / redirect URL genereren waarin je ook je Mollie payment ID & en `order_id` meestuurt.

Op het moment dat je webhook / redirect URL aangeroepen wordt kan je vervolgens:

1. De juiste order ophalen a.h.v. `order_id` en controleren of deze order in je database bestaat.
2. Checken of het payment ID in je DB staat en aan deze order is gekoppeld. Indien dat ook klopt, haal je de payment op bij Mollie.
3. Ten slotte check je de status van de payment en update je je order payment status a.h.v. de status van de Mollie payment.
