### ISSUE TITLE
Testing if customer id exists

### ISSUE THREAD

**Issue by ldestrooper** [mollie/mollie-api-ruby#128]
Is it possible to check if a customer id exists?

If i use Mollie::Customer.get i immediately get an exception.

**Comment by justincase** [comment]
You can rescue the exception:

```ruby
customer = begin
  Mollie::Customer.get('cst_8wmqcHMN4U')
rescue Mollie::RequestError => e
  if e['status'] == 404
    nil
  else
    raise
  end
end
```

@vernondegoede We could add a `NotFound` exception to rescue 404s
