### ISSUE TITLE
Creating iDEAL payment with QR code

### ISSUE THREAD

**Issue by madzhuga** [mollie/mollie-api-ruby#137]
According to [Mollie API](https://docs.mollie.com/reference/v2/payments-api/create-payment#response) we have to change API endpoint to have `https://api.mollie.com/v2/payments?include=details.qrCode`

Is there any option on `Mollie::Payment.create` to change endpoint that way and include QR code in a response?

**Comment by vernondegoede** [comment]
Hi @madzhuga,

```
payment_params = {
    amount: { value: '10.00', currency: 'EUR' },
    method: 'ideal',
    description: 'My first API payment',
    redirect_url: 'https://webshop.example.org/order/12345/',
    webhook_url: 'https://webshop.example.org/mollie-webhook/',
    api_key: 'live_<api_key>'
}

Mollie::Payment.create(
    payment_params,
    include: 'details.qrCode'
)

puts payment.inspect
```

**Comment by madzhuga** [comment]
Hi @vernondegoede! Thank you very much for answer!
