### ISSUE TITLE
Test environment limitations

### ISSUE THREAD

**Issue by madzhuga** [mollie/mollie-api-ruby#139]
Hi! 

That's not quite an issue but I didn't find a better way to contact API development team :) 

The question is: we're working on refund functionality and we need to have SEPA payments in 'paid' status. After I create SEPA payments - they stay in 'PENDING' mode and only things I can do is cancel them. Is there a way to move SEPA payments to 'paid' status? 

Thanks in advance! 
Max

**Comment by justincase** [comment]
Hi Max,

Recurring payments have a `changePaymentState` endpoint which allows you to change the payment state:

```ruby
payment = Mollie::Payment.get("tr_WDqYK6vllg")
payment.links['change_payment_state']['href']
=> "https://www.mollie.com/paymentscreen/testmode/?method=directdebit&token=xyz"
```

**Comment by madzhuga** [comment]
Hi Justin, 

Thank you very much for your answer. That's exactly what I need! 

Max
