### ISSUE TITLE
HTTP status code is not available in errors

### ISSUE THREAD

**Issue by gregbeech** [mollie/mollie-api-ruby#14]
The API status codes are [well documented](https://www.mollie.com/en/docs/errors#alle-mogelijke-statuscodes) however the API library currently discards the status code. This change captures the HTTP code and returns it on the raised error.

Having this status available is important to allow callers to distinguish between cases such as a payment not being found, credentials being invalid, or the gateway being down.

**Comment by gregbeech** [comment]
Note that #13 is a proposed fix for this issue.

**Comment by willemstuursma** [comment]
#13 is merged now, thanks.
