### ISSUE TITLE
Retrieve Payment linked to Order ?

### ISSUE THREAD

**Issue by Pyo25** [mollie/mollie-api-ruby#141]
Hi,

The doc says we can get payments linked to an Order using the `embed` parameter.
However it doesn't seem supported by this gem. 

How can I get payments linked to an order then? 

It's possible to get the order linked to a payment but not the inverse. Am I right?

Thank you!

**Comment by justincase** [comment]
Hi @Pyo25,

Correct, it's not yet supported by the Ruby client. In the meantime, there's a workaround that you could use: 
```
order = Mollie::Order.get("ord_kEn1PlbGa", embed: "payments")
payments = Mollie::List.new(
  {
    "_embedded" => order.attributes["_embedded"]
  },
  Mollie::Payment
)
```

Please keep in mind that `#attributes` should not be used in general and could break in future versions of the client.

**Comment by Pyo25** [comment]
Hi @justincase ,

A few months later (oops sorry), thank you for the workaround.
Not the best solution as it could be broken, but at least it works now.

Thank you!

**Comment by justincase** [comment]
Hi @Pyo25, 

You no longer need the workaround in v4.10.0 (tagged on GitHub - releases on rubygems.org are running behind due to #140).

```ruby
order = Mollie::Order.get("ord_kEn1PlbGa", embed: "payments")
payments = order.payments
```
