### ISSUE TITLE
Is this gem still under active development

### ISSUE THREAD

**Issue by gismoog** [mollie/mollie-api-ruby#142]
I am just starting a new project and would like to use mollie. But apparently this gem is no longer actively developed. Can I expect any updates in the near future or would it be better to use another payment service provider?

**Comment by wout** [comment]
This is the official gem, and it's pretty feature complete. That doesn't mean it's not actively developed. What's the reason for your conclusion?

**Comment by peterberkenbosch** [comment]
You can use this no problem @gismoog, however I understand your concern. Right now the best way to use this gem is to use the github link and not use the currently released gem. Work is in progress to enable to build and release pipeline again (see #140)

It is feature complete and stable and I can definitly recommend Mollie as a PSP.

**Comment by justincase** [comment]
Hi @gismoog,

I'm the maintainer of the Ruby gem on behalf of Mollie. As mentioned, the gem is, by and large, feature complete. Please let me know if there's anything missing or otherwise need help with.
