### ISSUE TITLE
422 Unprocessable Entity: The specified amount cannot be refunded

### ISSUE THREAD

**Issue by gerard76** [mollie/mollie-api-ruby#143]
If there is not enough balance on your account with the payment provider creating a refund can result in an HTTP `422` error.

In this case the refund will be queued (https://docs.mollie.com/payments/refunds) until sufficient balance is available again.

mollie-api-ruby raises a `Mollie::RequestError` https://github.com/mollie/mollie-api-ruby/blob/31a47aacc3a50b00fd5723d7838fa19cc435b299/lib/mollie/client.rb#L132 and does not return the queued refund information

**Comment by justincase** [comment]
Thanks @gerard76, I'll investigate.

**Comment by justincase** [comment]
Hi @gerard76, 

The API should return a `201 Created` in this scenario. Could you post the full exception message if you encounter a `422` again?

**Comment by gerard76** [comment]
Have not seen it since, but here is the backtrace from the incident on February 6th:

<img width="885" alt="Screenshot 2021-04-03 at 08 11 25" src="https://user-images.githubusercontent.com/765547/113470244-60600000-9454-11eb-9285-c2af98fbaab3.png">

The full message was `422 Unprocessable Entity: The specified amount cannot be refunded`

When reading the docs I did not expect a `201`, but a `4xx`:
<img width="917" alt="Screenshot 2021-04-03 at 08 15 35" src="https://user-images.githubusercontent.com/765547/113470302-dfedcf00-9454-11eb-9e3f-46f78b03d34c.png">

**Comment by justincase** [comment]
This error indicates the refund is higher than the remaining amount that can be refunded. To illustrate:

```ruby
payment = Mollie::Payment.get("tr_Vukgp8cAB7")

payment.amount_remaining
=> #<Mollie::Amount:0x007fd5e251c5b0 @attributes={"value"=>"10.00", "currency"=>"EUR"}, @value=0.1e2, @currency="EUR">

payment.refund!(amount: { value: '20.00', currency: 'EUR' })
Mollie::RequestError: 422 Unprocessable Entity: The specified amount cannot be refunded
```
Could this be the case here?

**Comment by gerard76** [comment]
Hrmmm, no, but you gave me an idea. There were multiple refunds requested, so the actual amount was right, but it was already requested....

Why are bugs more often something silly and stupid? I would like to solve bugs by being smart and cunning, not by finding out I have been stupid!

Thank you for your time!
