### ISSUE TITLE
Mollie::Method.all missing some methods

### ISSUE THREAD

**Issue by madzhuga** [mollie/mollie-api-ruby#146]
Is there a way to check account maximum amount value via API?

**Comment by justincase** [comment]
Hi @madzhuga,

`Mollie::Method#maximum_amount` contains the maximum amount that a payment method supports:
```
Mollie::Method.get('creditcard').maximum_amount
=> #<Mollie::Amount:0x007ffc52b005f8 @attributes={"value"=>"2000.00", "currency"=>"EUR"}, @value=0.2e4, @currency="EUR">
```

Or by filtering all payment methods:

```
Mollie::Method.all(amount: { value: '3000.00', currency: 'EUR' }).map { |method| method.id  }
=> ["ideal", "banktransfer"]
```

**Comment by madzhuga** [comment]
Hi @justincase 

Thank you for your replay. 

The thing is: when I call `Mollie::Method.all` it return iDEAL payment method only but if I call `Mollie::Method.get('directdebit')` - it returns values for that payment method. And then I see directdebit limit that is lower that the payment value caused 422 error. 

I will update the issue description.

**Comment by justincase** [comment]
`Mollie::Method.all` returns all payment methods that are enabled in your account. Could you confirm that's the case?

Perhaps a little confusing, `GET https://api.mollie.com/v2/methods/all` which returns all payment methods that Mollie offers and can be activated by the Organization, isn't implemented yet.

**Comment by madzhuga** [comment]
`Mollie::Method.all` returns only `activated` methods which is strange. 

We have `directdebit` with status `pending-review`. It allows us to create payments but does not allow us to see directdebit details in `Mollie::Method.all`. 

We have to use `Mollie::Method.get` - 3-4 requests to collect payment methods details instead of using one `Mollie::Method.all` request.

**Comment by justincase** [comment]
Hi @madzhuga,

I've opened mollie/mollie-api-ruby#149 to implement `/v2/methods/all`. This returns all payment methods available to your organization, including those with status `pending-review`.

**Comment by madzhuga** [comment]
:+1:
