### ISSUE TITLE
Support for new features, e.g. CancelUrl and Idempotency-Key

### ISSUE THREAD

**Issue by grekko** [mollie/mollie-api-ruby#160]
Dear Mollie-Team,

I am currently evaluating the Mollie Payment and Order API and corresponding ruby API client. I noticed that the Mollie API released new features in December 22 (see https://docs.mollie.com/changelog/v2/changelog#december-2022) which are not yet officially supported by this client. I am very much interested in using the `cancelUrl`-param and having support for `Idempotency-Key` in the ruby client.

What are your plans for officially supporting these features in the ruby client?

**Comment by justincase** [comment]
Hi @grekko,

I can likely add support for both over the weekend. Are there any other features you need that haven't been implemented yet?

**Comment by grekko** [comment]
Hey @justincase thanks for the quick response.

So far my use cases are already covered by the api client, thanks.

**Comment by justincase** [comment]
Hi @grekko,

Payments and orders now support the `cancel_url` attribute.

Note: the idempotency key functionality is an open beta feature. The exact implementation details may still be changed in the final release. Example usage:

```ruby
payment = Mollie::Payment.create(
  amount:       { value: '10.00', currency: 'EUR' },
  description:  'My first payment',
  redirect_url: 'https://webshop.example.org/order/12345/',
  webhook_url:  'https://webshop.example.org/payments/webhook/',
  metadata: {
    order_id: '12345'
  },
  idempotency_key: '<your-idempotency-key-here>'
)
```

Please let me know if this solves your requirements. Thanks!

**Comment by grekko** [comment]
> Please let me know if this solves your requirements. Thanks!

it very much does, thank you 🙇🏽
