### ISSUE TITLE
getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by Daniel304** [mollie/mollie-api-ruby#17]
On development it works perfectly but when it runs on the production and on our user acceptance environment it will throw the error: getaddrinfo: Name or service not known

        payment = mollie.payments.create(
          :amount       => number_to_currency(customer.amount, unit: ''),
          :description  => "testing",
          :redirectUrl  => url,
          :metadata     => {
            :order_id => customer.kenmerk
          }
        )

**Comment by paetor** [comment]
Maybe look at /etc/resolv.conf on your acceptance environment. I've had this issue in the past when resolv.conf is setup with multiple servers (which is normal), where the first one listed does not actually work (which is not normal, but can very well be the case). My experience is that getaddrinfo only tries the first one and then fails in the way you've described without ever trying the second.

**Comment by Daniel304** [comment]
We found the issue:
not working
  RestClient.proxy = 'http://proxy:8080'
working
  RestClient.proxy = 'http://proxy:8080/'
the problem lays in the / which should not be there !!!
