### ISSUE TITLE
Payment Links API

### ISSUE THREAD

**Issue by chrisun** [mollie/mollie-api-ruby#174]
It can be found in libraries for other languages, are there any plans to add it here? Thanks.

**Comment by fjbender** [comment]
Yes, we should add it here as well - I unfortunately just don't have a timeline yet... :)

**Comment by justincase** [comment]
Done! Thanks.

**Comment by JanDintel** [comment]
@justincase Hello again! :)

Could you publish the new version on Rubygems, so that I can use the API without having to track master? Thank you!

**Comment by justincase** [comment]
@JanDintel Hi, done!
