### ISSUE TITLE
Add support for partial refund

### ISSUE THREAD

**Issue by cynrichuys** [mollie/mollie-api-ruby#20]
For now only full refunds are possible

**Comment by Daanvm** [comment]
Hi @cynrichuys,
Thanks for your request and apologies for the late reply!

I'm not really a ruby developer myself, so I have to discus this with my colleagues, but I think you're right and we should add support for partial refunds.

**Comment by benoist** [comment]
perhaps milestone 2.0.1

**Comment by Lubmes** [comment]
Could someone in the meantime give an alternative way to transfer refunds?
I was told to use cURL and tried curl-to-ruby, faraday and rest-client, but nothing has worked.
Or maybe a monkey patch? That way you're not compromising the project.

**Comment by Lubmes** [comment]
For people having the same issue as me, I managed with some curl-to-ruby:

_No requires necessary_
```
def refund
  @invoice = Invoice.find(params[:id])

  uri = URI.parse("https://api.mollie.nl/v1/payments/#{@invoice.order.payment_id}/refunds"
  request = Net::HTTP::Post.new(uri)
  request["Authorization"] = "Bearer test_EygcTKUUPHnS85C4c5x2GAQ74rnyWr"
  request.set_form_data(
    "amount" => @invoice.paid_back_in_euros,
  )

  req_options = {
    use_ssl: uri.scheme == "https",
  }

  response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
    http.request(request)
  end

  redirect_to @invoice.order.customer
end
```

_Needed to convert integer into something mollie accepts_
```
def paid_back_in_euros
  sprintf("%03d", paid_back_cents.abs).insert(-3, ".")
end
```

**Comment by benoist** [comment]
Why do you say partial refunds aren't possible?
I haven't tried it yet, but I think this should be possible...

```ruby
client.payments_refunds.with_payment(payment).create(amount: 12)
```

**Comment by Lubmes** [comment]
The api isnt ready for that. Believe me, I have tried.

**Comment by benoist** [comment]
Is the Ruby API that isn't ready or the Mollie API itself?

**Comment by Lubmes** [comment]
Right, the mollie-api-ruby where this git is for.

**Comment by benoist** [comment]
I'm just trying to help and gathering all the facts before starting on the bug hunt :-)

**Comment by Lubmes** [comment]
I'm sorry. I am just a user myself, who also tries to contribute some in the process. 

With cURL you can make the api call for a refund with an amount and a description (as I show above).
The API itself, dedicated for Ruby (Rails, Sinatra, etc.) applications, that one doesn't yet do refunds with an amount.
Even had it checked with tech support, because I thought it would, similarly to how you create a payment. 

So there you have your bug :-) 
It's also the title of the issue: "partial" meaning "part of" - has got nothing to do with a rails partial.

**Comment by benoist** [comment]
I'm also just a user, but did a major refactor to the library. I will have a look at the bug this weekend. Thanks for the info, knowing the API call works is a big help.

**Comment by benoist** [comment]
```ruby
mollie = Mollie::API::Client.new("test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

payment = mollie.payments.get "tr_xxxxxxxxx"
pp mollie.payments_refunds.with(payment).all.count
pp mollie.payments_refunds.with(payment).create(amount: "0.10").payment.amount_refunded.to_f
pp mollie.payments_refunds.with(payment).all.count
```

This works for me with the 2.1.0 version.

**Comment by benoist** [comment]
It even works with real decimals instead of string

```ruby
mollie = Mollie::API::Client.new("test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxx")

payment = mollie.payments.get "tr_xxxxxxxxx"
pp mollie.payments_refunds.with(payment).all.count
pp mollie.payments_refunds.with(payment).create(amount: 0.10).payment.amount_refunded.to_f
pp mollie.payments_refunds.with(payment).all.count
```

**Comment by Lubmes** [comment]
Thank you, that totally worked. 
Also thanks for the all.count suggestion, I used that to check success and display an appropriate flash accordingly. 
Now my code looks a lot neater. 

'https://www.mollie.com/nl/docs/reference/refunds/create' nor tech support could help me with this.

**Comment by benoist** [comment]
Sure no problem. 

FYI

```ruby
refund = mollie.payments_refunds.with(payment).create(amount: 0.10)
```

This returns a refund object if the API call succeeds, if it fails it raises an exception. So checking the count for success won't work. You'd have to rescue the exception if you want to display a flash message like:

```ruby
begin
  payment = mollie.payments.get "tr_xxxxxxxxx"
  mollie.payments_refunds.with(payment).all.count
  mollie.payments_refunds.with(payment).create(amount: 0.10)
rescue Mollie::API::Exception => e
  flash[:alert] = e.message # or you're own custom error handling
end
```

**Comment by benoist** [comment]
@Daanvm this issue can be closed.
