### ISSUE TITLE
Changelogs and releases

### ISSUE THREAD

**Issue by rogierslag** [mollie/mollie-api-ruby#24]
Hi guys,

Awesome work on the gem. However it is becoming sometimes kinda difficult to determine whether to update the version used in our applications. Could you may be also publish Github releases or add a changelog? Its not really clear what has changed in v1.2.x for example, even though it already on rubygems.

Thnx!

**Comment by RicardoJ** [comment]
Hello Rogier,

You got a really good point here. I'll setup a changelog file and will keep the releases on GitHub also up to date. We somehow forgot these in this library, we're sorry.
