### ISSUE TITLE
Add pagination support to all resources

### ISSUE THREAD

**Issue by karensg** [mollie/mollie-api-ruby#25]
Hi,

How do I pass the `count` and `offset` parameters to Payment LIST method. So far I can see, it is not implemented as 

``` ruby
mollie.payments.all
```

 does not accept any parameters.

Thanks

**Comment by Daanvm** [comment]
Hi Karens,
Thanks for pointing this out and apologies for the late reply!

I think you're right, we should add support for pagination to all resources, not only the payments LIST method.

**Comment by benoist** [comment]
perhaps milestone 2.0.1

**Comment by Daanvm** [comment]
I agree, except that new features would require a MINOR version bump instead of a PATCH bump.

**Comment by karensg** [comment]
Hi guys,

Do you have any update on this functionality? I think it should be possible to pass all kind of parameters to the GET endpoints in general. It would make this gem much more usable.

Karens

**Comment by martijncasteel** [comment]
I would also like to now when it is possible to pass count and limit to the list function.

**Comment by Daanvm** [comment]
@brambokdam fixed this in PR #51, thanks!

I'll create a new release later today.

**Comment by Daanvm** [comment]
[Release 2.1.0](https://github.com/mollie/mollie-api-ruby/releases/tag/v2.1.0) is created. It's also released as [gem](https://rubygems.org/gems/mollie-api-ruby) at RubyGems.

**Comment by karensg** [comment]
Thanks, could finally send the locale parameter to the API.
