### ISSUE TITLE
Make the gem more Ruby-like

### ISSUE THREAD

**Issue by jurriaan** [mollie/mollie-api-ruby#3]
Please adhere to some sort of Ruby style guide (for example https://github.com/bbatsov/ruby-style-guide).

Things like 2 space soft-indent and `under_scored_method_names` are pretty common in the Ruby community.

It would also be great if you had a setter on the class for the API Key, something like this:
```ruby
Mollie::API::Client.api_key = 'key_here'
```

That would make the usage of this gem much more pleasant in for example Rails.

**Comment by rogierslag** [comment]
this issue could be closed based on https://github.com/mollie/mollie-api-ruby/pull/9 right?

**Comment by dennisdevulder** [comment]
Great improvement rogierslag, thanks!

**Comment by rogierslag** [comment]
I have to say that wasnt me though ;)

**Comment by willemstuursma** [comment]
Changes have been made in #9.
