### ISSUE TITLE
Update or remove dependencies

### ISSUE THREAD

**Issue by karensg** [mollie/mollie-api-ruby#30]
Please update `json` & `rest-client` dependencies as this gem is holding up the development of the applications

It also drops the support for Ruby `1.9` which is about time: 
<https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/>

**Comment by Daanvm** [comment]
Hi Karens,
Thanks for opening this issue and apologies for the late reply!

I'm not really a ruby developer myself, but I agree that when ruby v1.9.2 is already two years EOL it would be nice to update our client.

**Comment by Daanvm** [comment]
Note that both #29 and #32 will be fixed when we fix this issue.

**Comment by karensg** [comment]
Great to hear. Looking forward to the merge

**Comment by Daanvm** [comment]
We're currently working on a 2.0.0-release which will work with the latest versions of all dependencies.

**Comment by Daanvm** [comment]
Hi @benoist, there is already an issue for the dependencies.

As suggested in PR #36 we should remove the `rest-client` dependency and just use the stdlib `HTTP` library.

The `json` dependency is already removed in our 2.0.0 branch, as it's included in ruby by default since ruby 2.1.

**Comment by benoist** [comment]
Ok I will use this as the issue to create the PR

**Comment by Daanvm** [comment]
Fixed in PR #37
