### ISSUE TITLE
Example layout views?

### ISSUE THREAD

**Issue by Rubytastic2** [mollie/mollie-api-ruby#31]
Is there an complete example including a form and a view on how to implement ideal?
Totally not clear how to build the ideal frontend views.

**Comment by Daanvm** [comment]
Hi,

You don't have to build any iDEAL frontend views. In the [first example](https://github.com/mollie/mollie-api-ruby/blob/master/examples/1-new-payment.rb#L29-L42) you can see how to create a payment. You should [redirect the consumer to the payment URL](https://github.com/mollie/mollie-api-ruby/blob/master/examples/1-new-payment.rb#L49-L52) and we will do the rest of the work.

For more information, you can also look at [our documentation](https://www.mollie.com/en/docs/overview).

**Comment by Rubytastic2** [comment]
Thank you after running the sinatra code It worked.
Had to change the API key in every file.

Only problem now is the payment status is always "open" even if I select it failed, accepted

**Comment by Daanvm** [comment]
This is probably because of a problem with your webhook. The webhook is used to report status updates to your webserver.

When you send an e-mail to info@mollie.com with a payment ID we can help you sorting out this issue.
