### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by Daanvm** [mollie/mollie-api-ruby#39]
I would like to add unit tests to this repo. For as far as I know [test-unit (Test::Unit)](https://github.com/test-unit/test-unit/) is the go-to library for unit testing in Ruby.

**Comment by benoist** [comment]
Test::Unit and RSpec are both very popular. Test unit will do just fine. 
Using something like https://github.com/bblimke/webmock will also be a nice help to stub the API calls

**Comment by Daanvm** [comment]
I created a test suite in PR #40 with `Test::Unit` and `webmock`. Tests should still be added though.

**Comment by benoist** [comment]
I will probably have some time tonight to add tests

**Comment by Daanvm** [comment]
Fixed in PR #43
