### ISSUE TITLE
Invalid value for Accept-Encoding header

### ISSUE THREAD

**Issue by willemstuursma** [mollie/mollie-api-ruby#44]
An `Accept-Encoding` header is set. This header is used for indicating the transfer encoding (e.g. `deflate` or `gzip`. 

However, in the client is is set to `application/json`. This should be sent in the `Accept` header.

**Comment by benoist** [comment]
Fixed in 2.0.0

**Comment by Daanvm** [comment]
Thanks @benoist 
I also want to fix this in the 1.x release for all current ruby client users. It's only a small fix.
