### ISSUE TITLE
Add support for OAuth-only resources

### ISSUE THREAD

**Issue by rogierslag** [mollie/mollie-api-ruby#54]
The Ruby API docs mention that with OAuth tokens one can request the settlement information (https://www.mollie.com/nl/docs/reference/settlements/open)

However, even though the docs suggest it, these methods are not available in this API client. Will these soon be added?

**Comment by Daanvm** [comment]
Hi @rogierslag, thanks for reporting this issue.

There are currently no plans to add support for an OAuth authentication flow in the Ruby client. However, when you manage the OAuth flow yourself, you can just pass the Access Token to this client.

Adding the OAuth-only resources shouldn't be too much effort. If that would be sufficient for you, I'll see if I can add them anytime soon.
