### ISSUE TITLE
keys not camelized for GET requests

### ISSUE THREAD

**Issue by derekkraan** [mollie/mollie-api-ruby#62]
Request keys are camelized for POST requests, but not for GET requests. I'm not sure if there are certain query params that should *not* be camelized, but there certainly are other params that *should* (eg, `profile_id`).

See https://github.com/mollie/mollie-api-ruby/blob/master/lib/mollie/api/client.rb#L91
and https://github.com/mollie/mollie-api-ruby/blob/master/lib/mollie/api/client.rb#L99

**Comment by benoist** [comment]
Thank you for reporting. Get requests are now camelized in the master branch.

**Comment by derekkraan** [comment]
Thanks!
