### ISSUE TITLE
uninitialized constant Mollie::API::Client::Net

### ISSUE THREAD

**Issue by todorus** [mollie/mollie-api-ruby#63]
I am trying to add this gem to my Rails app, but I am hitting a roadblock with this namespacing. It doesn't matter how I try, my app just cannot find the Net class.

The code can be viewed at https://github.com/Lindy-what/lindy-admin/tree/mollie
The client is required in [rails-app/config/application.rb](https://github.com/Lindy-what/lindy-admin/blob/mollie/rails-app/config/application.rb)
The Payment model will try to create a mollie payment, but it will fail with this error. The Payment model is defined in [rails-app/models/payment.rb ](https://github.com/Lindy-what/lindy-admin/blob/mollie/rails-app/app/models/payment.rb)

I find it weird that others haven't run into this. Then again, others seem to be running an older version. I am yet to try if this makes a difference.

**Comment by bobvanoorschot** [comment]
I ran into the same problem a couple of months ago, after searching for hours I found out I was missing the Net class from rails. Require this above the code
`require 'net/http'`

**Comment by benoist** [comment]
This was fixed in the master version on the 31st of may.
There are other issues with version 2.2.0 so I would recommend to use the master branch for now.
I cant push new versions to rubygems (I'm not a mollie employee), but master should be ready to go.

**Comment by todorus** [comment]
Allright! Tnx for the quick feedback guys.

I am ok to use the master for now, but say I want to use this in production in... less then a month. I don't want my gemfile to referring to a target that's in active development. When would an employee of Mollie be able to push this to rubygems?

**Comment by benoist** [comment]
I can tag a new version in github and keep that stable.

**Comment by benoist** [comment]
I've created a v2.2.1 tag, let me know if you run into other issues.
