### ISSUE TITLE
uninitialized constant Mollie::API::Client::Net

### ISSUE THREAD

**Issue by iDuuck** [mollie/mollie-api-ruby#64]
When using the gem in Ruby on Rails I am always getting the following error when initiaiting a payment (I think it has something to do with the Net/HTTPs Library):

```
uninitialized constant Mollie::API::Client::Net
```

**Comment by benoist** [comment]
Hi Thanks for reaching out. This is fixed in version 2.2.1. This gem version will be released by mollie soon. In the mean time you can use the GitHub tag 2.2.1. Let me know if you have other issues.

**Comment by iDuuck** [comment]
Wow! Thanks for the *instant* reply! Will try later

- Nick
________________________________

**Comment by Daanvm** [comment]
I just released version 2.2.1 on https://rubygems.org/gems/mollie-api-ruby
