### ISSUE TITLE
Definition of paid? by direct debit transaction

### ISSUE THREAD

**Issue by MathijsK93** [mollie/mollie-api-ruby#67]
What exactly is the definition of `paid?` in case of a charged back direct debit transaction?

The `paid?` methods checks if `paid_datetime` is set, but does it not have to check if the status equals `paid`? For example i have a direct debit transaction which was previously paid, but after a charge back the method `paid?` still returns that the transaction is paid.

In my opinion `paid` means that the transaction is successfully paid, except if the transaction is charged back.

The `paid?` method as decribed in the gem:
https://github.com/mollie/mollie-api-ruby/blob/92a2778a91928e9d5b0539418485e6f2d5e2b24d/lib/mollie/api/object/payment.rb#L55-L57

**Comment by benoist** [comment]
@Daanvm @willemstuursma do you agree? If so I can change it

**Comment by Daanvm** [comment]
Sorry for the late reply. I've started an internal discussion whether we want to change this or not. For now we've decided to not change this method. If someone has additional arguments why this method should be changed, please let us know.

@MathijsK93 I do understand your concerns. However, there are other use-cases where you want to check if the payment was once paid, for example if you want to check whether you should display the customer details in a list of payments.

Secondly, the `paid?` method has currently the same method across all our clients (PHP, Python, Node and Ruby). We like to keep these method consistent.

There are currently a lot of customers depending on our current behaviour, so we don't feel comfortable changing it now. Any change in the functionality of this method should result in a new major release. We don't think it's worth a new release right now.

Of course you can always work around this issue by checking both `paid?`, `refunded?` and `charged_back?`.

**Comment by MathijsK93** [comment]
@Daanvm Thanks for your answer. I fully understand your decision. For me it is a little change, i just wanted to bring it up for discussion.
