### ISSUE TITLE
Adding mollie to spree

### ISSUE THREAD

**Issue by salman15** [mollie/mollie-api-ruby#69]
Not sure where to post this question.

I want to add mollie to spree, but i've no idea how to do this.

**Comment by benoist** [comment]
I believe that would require creating a spree extension. This is not a very easy task to do.
I think @Daanvm would have to do some research about the possibilities to add support for that.

**Comment by salman15** [comment]
That would be splendid, I guess I have to wait for his reply

**Comment by Daanvm** [comment]
Hi @salman15, we currently don't have any plans to build a Spree extension ourselves. I have no experience with Spree, so I did some research and this is what I've found.

**Existing extensions**
I found some existing Spree extensions for Mollie, but they are all a few years old and not well maintained. I've no idea if they do actually work. You could have a look at them and if you're a developer yourself you might be able update them.

* [pero-ict-solutions/spree_mollie](https://github.com/pero-ict-solutions/spree_mollie)
* [javereec/spree_mollie](https://github.com/javereec/spree_mollie)
* [ttcremers/spree_mollie](https://github.com/ttcremers/spree_mollie)
* [pero-ict-solutions/spree-mollie-ideal](https://github.com/pero-ict-solutions/spree-mollie-ideal)

**Building your own extension**
You can develop your own Spree gateway. There is [not much documentation](https://guides.spreecommerce.org/developer/payments.html#adding-your-custom-gateway), but they suggest to [use this gateways as an example](https://github.com/spree-contrib/spree_braintree_vzero).

**Use the ActiveMerchant wrapper**
There is [a wrapper to use ActiveMerchant gateways in Spree](https://github.com/spree/spree_gateway). Mollie is not included in the ActiveMerchant library, but you might be able to find another Mollie ActiveMerchant integration.


Note that I don't have any experience with any of the above suggestions, so if you have any questions you should ask them at the owners/maintainers of the products themselves.

**Comment by vernondegoede** [comment]
We just released the official Mollie payment gateway for Spree Commerce.

Check out the repo: https://github.com/mollie/spree-mollie-gateway

**Comment by salman15** [comment]
Great, looking forward to using it! :)
