### ISSUE TITLE
uninitialized constant Mollie (NameError)

### ISSUE THREAD

**Issue by asgerb** [mollie/mollie-api-ruby#70]
Hey there,
I'm trying to set up Mollie with a new Rails (`5.1.4`) app.
I add the gem to my Gemfile:
```RUBY
gem 'mollie-api-ruby'
```
and add an initializer like so:
```RUBY
Mollie::Client.instance.api_key = ENV['MOLLIE_API_KEY']
```
This causes an `uninitialized constant Mollie (NameError)` when booting up the app.

It seems there are problems loading the files since if I try to `require 'mollie-api-ruby'` I get:
```
cannot load such file -- mollie-api-ruby (LoadError)
```

Looking at your `gemspec` I see you're using git to determine the files included in the package: 
```RUBY
s.files = `git ls-files`.split("\n")
```
I'm not sure, but this might be where the problem is. Perhaps it would be better to use a pure ruby  method. It seems to be the standard from quickly looking at various gemspecs, ([Sprockets](https://github.com/rails/sprockets/blob/master/sprockets.gemspec#L11) is a quick example).

Looking forward to getting started with Mollie 🙂

**Comment by benoist** [comment]
It looks like you're trying to set it up using the new API, but you've probably installed the 2.x version.

If you are starting a new implementation I would advise you to use the github repo

```
gem 'mollie-api-ruby', github: 'mollie/mollie-api-ruby', tag: 'v3.1.0'
```

If you want to use the version 2.x version you can view the docs here

https://github.com/mollie/mollie-api-ruby/tree/2.2.x

**Comment by asgerb** [comment]
Thank you, that did the trick!
How come the version is not pushed to Rubygems yet?
Just curious 🙂

**Comment by benoist** [comment]
Great! The last changes for the new release were made yesterday and it needs some modifications to the documentation on the website before it can be released.

**Comment by asgerb** [comment]
Cool, thanks a lot for the super fast response!

**Comment by tilsammans** [comment]
@benoist still not pushed. Since the README states the instructions for 3.x, a confusing situation has arisen. Do you think you could publish 3.x any time soon?

**Comment by ldestrooper** [comment]
It is quite confusing with the different versions and readme's
