### ISSUE TITLE
Unauthorized request

### ISSUE THREAD

**Issue by ldestrooper** [mollie/mollie-api-ruby#71]
Bij het gebruiken van Mollie in Rails krijg ik een Unauthorized request error door het volgende:

`customer = Mollie::Customer.create(name: first_name, email: email)`

mijn test API is nochtans correct, dus ik begrijp niet waarom ik deze error krijg, enig idee?

**Comment by benoist** [comment]
Het betekent dat je api_key niet goed is. Hoe heb je deze geconfigureerd? Welke versie gebruik je?

**Comment by ldestrooper** [comment]
Wow dat was snel :-)

Gemfile:
`gem 'mollie-api-ruby', github: 'mollie/mollie-api-ruby', tag: 'v3.1.0'`

Secrets.yml:
`development:
mollie_secret_key: test_u9jAsrh8kxhEmSe6D35gRh4Nzjg2qb

production:
mollie_secret_key: <%= ENV["MOLLIE_SECRET_KEY"] %>`

Mollie.rb:
`Mollie::Client.api_key = Rails.application.secrets.mollie_secret_key`

**Comment by benoist** [comment]
Er zat een bug in de v3.1.0 tag en was al gefixt in master.

Ik heb tag v3.1.1 gepushed, configuratie is nu als volgt:

```ruby
Mollie::Client.configure do |config|
  config.api_key = '<your-api-key>'
end
```

**Comment by ldestrooper** [comment]
Heb de 3.1.1 geinstalleerd en was inderdaad die bug, bedankt voor de snelle hulp! 👌
