### ISSUE TITLE
Release 3.1.1

### ISSUE THREAD

**Issue by benoist** [mollie/mollie-api-ruby#75]
@Daanvm can you release version 3.1.1

**Comment by Smitsel** [comment]
Hi @benoist, could u draft us a changelog for the release?
Then i can take care of this for u.

**Comment by benoist** [comment]
- All new API based on resource models
- Support nested resources
- Added relation model and configured relations for customers, payments
- Added content type to client
- Pass options array to get
- Pass extra options to all method
- Camelize get params closes #62
- Added refunds resource and added more examples
- Added gift card method
- Added all new examples with swagger documentation
- Add queued status and handy accessor to refunds

**Comment by willemstuursma** [comment]
@mvdpanne can we automate releases just as with pip?

**Comment by Smitsel** [comment]
Just drafted a new release, will take care of pushing it to ruby gems.

**Comment by Zyphrax** [comment]
@benoist Where can I find an upgrade guide from v2 to v3?
I assume that this new major version breaks code? It would be nice to know what/how/where?

**Comment by mvdpanne** [comment]
I just added configuration details for automatic deployment to RubyGems in `.travis.yml` and pushed it to master. When a new tag/release is pushed to GitHub, Travis CI will take care of publishing it on RubyGems.

**Comment by Zyphrax** [comment]
@mvdpanne @willemstuursma Where can I find an upgrade guide from v2 to v3?

**Comment by benoist** [comment]
@Zyphrax an upgrade guide will be provided soon

**Comment by benoist** [comment]
@Zyphrax I've added a migration guide to the readme
