### ISSUE TITLE
No 3.0 release?

### ISSUE THREAD

**Issue by mvz** [mollie/mollie-api-ruby#79]
I'm trying to upgrade to the 3.x series of this gem, and according to the changelog, there should be a 3.0.0 release where the old API is present but deprecated. However, this version is not available on rubygems, making migration harder.

**Comment by vernondegoede** [comment]
Hi @mvz,

I'm afraid something went wrong on our side. The first 3.x version that was published to Rubygems is 3.1.0: https://rubygems.org/gems/mollie-api-ruby/versions. 

Also, there doesn't seem to be a tag created in Git. We [do have a `3.0.x` branch](https://github.com/mollie/mollie-api-ruby/tree/3.0.x), though.

If you would like to use the `3.0.x` branch in your project, add the following line to your Gemfile:

```ruby
:git => 'https://github.com/mollie/mollie-api-ruby.git', :branch => '3.0.x'
```

We do have a [migration guide](https://github.com/mollie/mollie-api-ruby/blob/master/docs/migration_v2_2_x.md) which makes it easier to migrate from 2.x to 3.x.
