### ISSUE TITLE
Client cancels order to pick different payment method

### ISSUE THREAD

**Issue by ldestrooper** [mollie/mollie-api-ruby#80]
Is there a payments url parameter we can use to give the client a proper redirect back to the checkout page to choose a different payment method instead of continuing to the regular redirect url? @benoist

**Comment by vernondegoede** [comment]
Mollie only accepts a `webhookUrl` and a `redirectUrl` when creating a new payment.

When a shopper cancels a payment during the Mollie checkout process, we call the `webhookUrl` to inform you of a payment state change. You should retrieve the current status of the payment at this point.

The moment your shopper is redirected to the `redirectUrl` again, you can simply create a new payment and redirect your shopper back to the `checkoutUrl` that was returned in your new payment response.

More information about the payment process [can be found here](https://docs.mollie.com/payments/overview).
