### ISSUE TITLE
Test issuer is invalid

### ISSUE THREAD

**Issue by elfassy** [mollie/mollie-api-ruby#81]
```
> Mollie::Issuer.get("ideal_TESTNL99",  api_key: "test_...")
Mollie::Exception: The issuer is invalid
```
The test issuer `ideal_TESTNL99` is listed as invalid, am i missing something?

**Comment by willemstuursma** [comment]
The test issuer has been removed. 

Please use one of the other iDEAL issuers. They can be retrieved using the issuers API. 

https://www.mollie.com/en/developers/changelog
