### ISSUE TITLE
Adhere to Ruby Style Guide

### ISSUE THREAD

**Issue by vernondegoede** [mollie/mollie-api-ruby#83]
This client currently does not follow any style guide, which results in lots of code style inconsistencies within the source code (alignment, single/double quotes, etc.).

I would like this client to adhere to the community driven [Ruby Style Guide](https://github.com/rubocop-hq/ruby-style-guide). 

One way to enforce this would be to add [Rubocop](https://github.com/rubocop-hq/rubocop) as a pre-commit hook / Travis build step and statically analyze the source code after every push.

Another option would be to add [Codeclimate](https://codeclimate.com/quality/) as a Github app to this repository which constantly scans the repo and its code quality. It's free for open source projects.

I'd prefer to go with the Codeclimate option.

**Comment by justincase** [comment]
Can we initialise with `--auto-gen-config` to create a `.rubocop_todo.yml` config and fix things from there?

**Comment by vernondegoede** [comment]
@justincase is this something that you can pick up?

**Comment by justincase** [comment]
@vernondegoede Sure! 👍
