### ISSUE TITLE
Minor API changes

### ISSUE THREAD

**Issue by vernondegoede** [mollie/mollie-api-ruby#95]
There are a couple of new fields for the GET Payment response:

- `amountCaptured`
- `_.links.captures`. Can we list all captures using the `captures` method, just like we do with refunds? https://github.com/mollie/mollie-api-ruby/blob/master/lib/mollie/payment.rb#L170

I also noticed that there is currently no helper method to check whether a payment is refunded. Can we add the following helper methods to the payment class:

- `refunded?`, which should check whether `amountRefunded` is > 0.

There are a couple of new fields for Subscriptions:
- `nextPaymentDate`
- `mandateId`

Can we add these to the `attr_accessor` list?

**Comment by justincase** [comment]
Sounds good, I’ll take a look over the weekend.
