### ISSUE TITLE
Invalid endpoint for creating mandates

### ISSUE THREAD

**Issue by MathijsK93** [mollie/mollie-api-ruby#99]
I am migrating the mollie gem in our codebase from 2.2.1 to 4.1.2 and having issues when creating a mandate for an existing customer.

I use `Mollie::Customer::Mandate.create` for creating customer mandates, but the endpoint used for this request is `http://api.mollie.com:443/v2/mandates`. According to the API reference it must be: `https://api.mollie.com/v2/customers/*customerId*/mandates`.
 
See my debug log:
```
[20] pry(main)> Mollie::Customer::Mandate.create
D, [2018-11-20T16:16:24.549115 #90196] DEBUG -- : [httplog] Connecting: api.mollie.com:443
D, [2018-11-20T16:16:24.620042 #90196] DEBUG -- : [httplog] Sending: POST http://api.mollie.com:443/v2/mandates
D, [2018-11-20T16:16:24.620381 #90196] DEBUG -- : [httplog] Data: {}
D, [2018-11-20T16:16:24.649258 #90196] DEBUG -- : [httplog] Status: 404
D, [2018-11-20T16:16:24.649447 #90196] DEBUG -- : [httplog] Benchmark: 0.028052 seconds
D, [2018-11-20T16:16:24.649679 #90196] DEBUG -- : [httplog] Response:
{"status":404,"title":"Not Found","detail":"Invalid resource endpoint","_links":{"documentation":{"href":"https://docs.mollie.com/guides/handling-errors","type":"text/html"}}}
Mollie::RequestError: 404 Not Found: Invalid resource endpoint
```

**Comment by vernondegoede** [comment]
@justincase Can you take a look?

**Comment by justincase** [comment]
Hi @MathijsK93, creating a mandate requires a number of mandatory attributes. Could you try the following?

```ruby
mandate = Mollie::Customer::Mandate.create(
  customer_id:       'cst_4qqhO89gsT',
  method:            'directdebit',
  consumer_name:     'John Doe',
  consumer_account:  'NL55INGB0000000000'
)
```

**Comment by MathijsK93** [comment]
Hi @justincase thanks for your reply.
My rspec factory had a empty `customer_id` which resulted in an incorrect URL to the API.
Sorry for the inconvenience!
